# Generated by Django 4.0.3 on 2022-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('manager_name', models.CharField(max_length=50)),
                ('outlet_image', models.ImageField(upload_to='outlet_image')),
            ],
        ),
    ]
