# Generated by Django 4.0.1 on 2022-04-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='outlet_image',
        ),
    ]
