# Generated by Django 4.0.3 on 2022-04-13 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_outlettime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutletTime',
        ),
        migrations.AddField(
            model_name='outlet',
            name='closing_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outlet',
            name='opening_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
