# Generated by Django 4.0.3 on 2022-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_delete_outlettime_outlet_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='off_day',
            field=models.CharField(default='Friday', max_length=50),
        ),
    ]
