# Generated by Django 4.0.3 on 2022-04-13 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_outlet_off_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='address_latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address_longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='closing_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='opening_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
